site_name: PRiSM
site_author: Henry Pigot, Paulo Lisboa, Johan Nilsson

theme:
  name: "material"

nav:
  - Home: index.md
  - README: README_copy.md
  - Docs: reference.md 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy